### ISSUE TITLE
Some questions about project start-up

### ISSUE THREAD

**Issue by mmungdong** [aide-cloud/prometheus-manager#8]
I'm having problems starting the project.
`make init` is okay
but the `make local app=app/prom_server`  I had some problems with gcc with this command, here are some keywords：
- confluent-kafka-go/v2@v2.3.0/kafka/librdkafka_vendor
- undefined reference to `__imp_WSAStartup'
my gcc version is v8.1.0
So I upgraded my gcc version: v12.1.0，but there's a new error about gcc：
![Snipaste_2024-01-28_12-45-09](https://github.com/aide-cloud/prometheus-manager/assets/57240853/671a583e-bc32-40c9-99c4-59c404f5baa8)

Is my version of gcc not compatible?

**Comment by aide-cloud** [comment]
This problem is caused by the dependency problem of the kafka package used, you can refer to the description of this package to improve, because I do not have a win environment, so I can not give you effective advice.[kafka](https://github.com/confluentinc/confluent-kafka-go)

**Comment by mmungdong** [comment]
[https://github.com/aide-cloud/prometheus-manager/blob/7842ea9ebcad42cb5eb3165d7fb3e9ce0ea89d48/app/prom_server/Makefile#L24](url)
Here I think `. / configs_local` should give a demo directly, and the configuration file should be in the project, such as `. / app/prom_server/configs/config.yaml`, And the README should remind users to start some middleware, such as mysql and kafka, locally in advance

**Comment by mmungdong** [comment]
https://github.com/aide-cloud/prometheus-manager/blob/7842ea9ebcad42cb5eb3165d7fb3e9ce0ea89d48/app/prom_server/Makefile#L24

Here I think . / configs_local should give a demo directly, and the configuration file should be in the project, such as . / app/prom_server/configs/config.yaml, And the README should remind users to start some middleware, such as mysql and kafka, locally in advance

**Comment by mmungdong** [comment]
There will be problems when building the binary of this project's components directly under windows, it is recommended to use the container approach.
